apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: dev
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-monitor
  namespace: prod
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s

