# External Secret for GCP Secret Manager
# Uncomment after installing External Secrets Operator

# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: {{ .Chart.Name }}-secret
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     name: gcpsm-secret-store
#     kind: SecretStore
#   target:
#     name: {{ .Chart.Name }}-secret
#   data:
#   - secretKey: SYS_ENV
#     remoteRef:
#       key: sys-env

